parameters:
#    esprit_demo.example.class: Esprit\DemoBundle\Example

services:
#    esprit_demo.example:
#        class: %esprit_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
